# Generated by Django 5.1 on 2024-11-26 05:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(default='admin@gmail.com', max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(default='Dhaka', max_length=255, null=True)),
                ('apartment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('abandoned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Color1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Maroon', 'Maroon'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Teal', 'Teal'), ('Lime', 'Lime'), ('Beige', 'Beige'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Violet', 'Violet'), ('Indigo', 'Indigo'), ('Turquoise', 'Turquoise'), ('Lavender', 'Lavender'), ('Crimson', 'Crimson'), ('Coral', 'Coral'), ('Peach', 'Peach'), ('Mint', 'Mint'), ('Ivory', 'Ivory'), ('Charcoal', 'Charcoal'), ('Burgundy', 'Burgundy'), ('Rose', 'Rose'), ('Emerald', 'Emerald'), ('Saffron', 'Saffron'), ('Azure', 'Azure')], max_length=100, null=True)),
                ('color_code', models.CharField(blank=True, choices=[('#000000', '#000000'), ('#FFFFFF', '#FFFFFF'), ('#FF0000', '#FF0000'), ('#0000FF', '#0000FF'), ('#008000', '#008000'), ('#FFFF00', '#FFFF00'), ('#FFA500', '#FFA500'), ('#800080', '#800080'), ('#FFC0CB', '#FFC0CB'), ('#808080', '#808080'), ('#A52A2A', '#A52A2A'), ('#00FFFF', '#00FFFF'), ('#FF00FF', '#FF00FF'), ('#800000', '#800000'), ('#000080', '#000080'), ('#808000', '#808000'), ('#008080', '#008080'), ('#00FF00', '#00FF00'), ('#F5F5DC', '#F5F5DC'), ('#FFD700', '#FFD700'), ('#C0C0C0', '#C0C0C0'), ('#EE82EE', '#EE82EE'), ('#4B0082', '#4B0082'), ('#40E0D0', '#40E0D0'), ('#E6E6FA', '#E6E6FA'), ('#DC143C', '#DC143C'), ('#FF7F50', '#FF7F50'), ('#FFE5B4', '#FFE5B4'), ('#98FF98', '#98FF98'), ('#FFFFF0', '#FFFFF0'), ('#36454F', '#36454F'), ('#800020', '#800020'), ('#FF007F', '#FF007F'), ('#50C878', '#50C878'), ('#F4C430', '#F4C430'), ('#007FFF', '#007FFF')], max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_image')),
            ],
        ),
        migrations.CreateModel(
            name='Color10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Maroon', 'Maroon'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Teal', 'Teal'), ('Lime', 'Lime'), ('Beige', 'Beige'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Violet', 'Violet'), ('Indigo', 'Indigo'), ('Turquoise', 'Turquoise'), ('Lavender', 'Lavender'), ('Crimson', 'Crimson'), ('Coral', 'Coral'), ('Peach', 'Peach'), ('Mint', 'Mint'), ('Ivory', 'Ivory'), ('Charcoal', 'Charcoal'), ('Burgundy', 'Burgundy'), ('Rose', 'Rose'), ('Emerald', 'Emerald'), ('Saffron', 'Saffron'), ('Azure', 'Azure')], max_length=100, null=True)),
                ('color_code', models.CharField(blank=True, choices=[('#000000', '#000000'), ('#FFFFFF', '#FFFFFF'), ('#FF0000', '#FF0000'), ('#0000FF', '#0000FF'), ('#008000', '#008000'), ('#FFFF00', '#FFFF00'), ('#FFA500', '#FFA500'), ('#800080', '#800080'), ('#FFC0CB', '#FFC0CB'), ('#808080', '#808080'), ('#A52A2A', '#A52A2A'), ('#00FFFF', '#00FFFF'), ('#FF00FF', '#FF00FF'), ('#800000', '#800000'), ('#000080', '#000080'), ('#808000', '#808000'), ('#008080', '#008080'), ('#00FF00', '#00FF00'), ('#F5F5DC', '#F5F5DC'), ('#FFD700', '#FFD700'), ('#C0C0C0', '#C0C0C0'), ('#EE82EE', '#EE82EE'), ('#4B0082', '#4B0082'), ('#40E0D0', '#40E0D0'), ('#E6E6FA', '#E6E6FA'), ('#DC143C', '#DC143C'), ('#FF7F50', '#FF7F50'), ('#FFE5B4', '#FFE5B4'), ('#98FF98', '#98FF98'), ('#FFFFF0', '#FFFFF0'), ('#36454F', '#36454F'), ('#800020', '#800020'), ('#FF007F', '#FF007F'), ('#50C878', '#50C878'), ('#F4C430', '#F4C430'), ('#007FFF', '#007FFF')], max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_image')),
            ],
        ),
        migrations.CreateModel(
            name='Color2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Maroon', 'Maroon'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Teal', 'Teal'), ('Lime', 'Lime'), ('Beige', 'Beige'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Violet', 'Violet'), ('Indigo', 'Indigo'), ('Turquoise', 'Turquoise'), ('Lavender', 'Lavender'), ('Crimson', 'Crimson'), ('Coral', 'Coral'), ('Peach', 'Peach'), ('Mint', 'Mint'), ('Ivory', 'Ivory'), ('Charcoal', 'Charcoal'), ('Burgundy', 'Burgundy'), ('Rose', 'Rose'), ('Emerald', 'Emerald'), ('Saffron', 'Saffron'), ('Azure', 'Azure')], max_length=100, null=True)),
                ('color_code', models.CharField(blank=True, choices=[('#000000', '#000000'), ('#FFFFFF', '#FFFFFF'), ('#FF0000', '#FF0000'), ('#0000FF', '#0000FF'), ('#008000', '#008000'), ('#FFFF00', '#FFFF00'), ('#FFA500', '#FFA500'), ('#800080', '#800080'), ('#FFC0CB', '#FFC0CB'), ('#808080', '#808080'), ('#A52A2A', '#A52A2A'), ('#00FFFF', '#00FFFF'), ('#FF00FF', '#FF00FF'), ('#800000', '#800000'), ('#000080', '#000080'), ('#808000', '#808000'), ('#008080', '#008080'), ('#00FF00', '#00FF00'), ('#F5F5DC', '#F5F5DC'), ('#FFD700', '#FFD700'), ('#C0C0C0', '#C0C0C0'), ('#EE82EE', '#EE82EE'), ('#4B0082', '#4B0082'), ('#40E0D0', '#40E0D0'), ('#E6E6FA', '#E6E6FA'), ('#DC143C', '#DC143C'), ('#FF7F50', '#FF7F50'), ('#FFE5B4', '#FFE5B4'), ('#98FF98', '#98FF98'), ('#FFFFF0', '#FFFFF0'), ('#36454F', '#36454F'), ('#800020', '#800020'), ('#FF007F', '#FF007F'), ('#50C878', '#50C878'), ('#F4C430', '#F4C430'), ('#007FFF', '#007FFF')], max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_image')),
            ],
        ),
        migrations.CreateModel(
            name='Color3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Maroon', 'Maroon'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Teal', 'Teal'), ('Lime', 'Lime'), ('Beige', 'Beige'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Violet', 'Violet'), ('Indigo', 'Indigo'), ('Turquoise', 'Turquoise'), ('Lavender', 'Lavender'), ('Crimson', 'Crimson'), ('Coral', 'Coral'), ('Peach', 'Peach'), ('Mint', 'Mint'), ('Ivory', 'Ivory'), ('Charcoal', 'Charcoal'), ('Burgundy', 'Burgundy'), ('Rose', 'Rose'), ('Emerald', 'Emerald'), ('Saffron', 'Saffron'), ('Azure', 'Azure')], max_length=100, null=True)),
                ('color_code', models.CharField(blank=True, choices=[('#000000', '#000000'), ('#FFFFFF', '#FFFFFF'), ('#FF0000', '#FF0000'), ('#0000FF', '#0000FF'), ('#008000', '#008000'), ('#FFFF00', '#FFFF00'), ('#FFA500', '#FFA500'), ('#800080', '#800080'), ('#FFC0CB', '#FFC0CB'), ('#808080', '#808080'), ('#A52A2A', '#A52A2A'), ('#00FFFF', '#00FFFF'), ('#FF00FF', '#FF00FF'), ('#800000', '#800000'), ('#000080', '#000080'), ('#808000', '#808000'), ('#008080', '#008080'), ('#00FF00', '#00FF00'), ('#F5F5DC', '#F5F5DC'), ('#FFD700', '#FFD700'), ('#C0C0C0', '#C0C0C0'), ('#EE82EE', '#EE82EE'), ('#4B0082', '#4B0082'), ('#40E0D0', '#40E0D0'), ('#E6E6FA', '#E6E6FA'), ('#DC143C', '#DC143C'), ('#FF7F50', '#FF7F50'), ('#FFE5B4', '#FFE5B4'), ('#98FF98', '#98FF98'), ('#FFFFF0', '#FFFFF0'), ('#36454F', '#36454F'), ('#800020', '#800020'), ('#FF007F', '#FF007F'), ('#50C878', '#50C878'), ('#F4C430', '#F4C430'), ('#007FFF', '#007FFF')], max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_image')),
            ],
        ),
        migrations.CreateModel(
            name='Color4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Maroon', 'Maroon'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Teal', 'Teal'), ('Lime', 'Lime'), ('Beige', 'Beige'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Violet', 'Violet'), ('Indigo', 'Indigo'), ('Turquoise', 'Turquoise'), ('Lavender', 'Lavender'), ('Crimson', 'Crimson'), ('Coral', 'Coral'), ('Peach', 'Peach'), ('Mint', 'Mint'), ('Ivory', 'Ivory'), ('Charcoal', 'Charcoal'), ('Burgundy', 'Burgundy'), ('Rose', 'Rose'), ('Emerald', 'Emerald'), ('Saffron', 'Saffron'), ('Azure', 'Azure')], max_length=100, null=True)),
                ('color_code', models.CharField(blank=True, choices=[('#000000', '#000000'), ('#FFFFFF', '#FFFFFF'), ('#FF0000', '#FF0000'), ('#0000FF', '#0000FF'), ('#008000', '#008000'), ('#FFFF00', '#FFFF00'), ('#FFA500', '#FFA500'), ('#800080', '#800080'), ('#FFC0CB', '#FFC0CB'), ('#808080', '#808080'), ('#A52A2A', '#A52A2A'), ('#00FFFF', '#00FFFF'), ('#FF00FF', '#FF00FF'), ('#800000', '#800000'), ('#000080', '#000080'), ('#808000', '#808000'), ('#008080', '#008080'), ('#00FF00', '#00FF00'), ('#F5F5DC', '#F5F5DC'), ('#FFD700', '#FFD700'), ('#C0C0C0', '#C0C0C0'), ('#EE82EE', '#EE82EE'), ('#4B0082', '#4B0082'), ('#40E0D0', '#40E0D0'), ('#E6E6FA', '#E6E6FA'), ('#DC143C', '#DC143C'), ('#FF7F50', '#FF7F50'), ('#FFE5B4', '#FFE5B4'), ('#98FF98', '#98FF98'), ('#FFFFF0', '#FFFFF0'), ('#36454F', '#36454F'), ('#800020', '#800020'), ('#FF007F', '#FF007F'), ('#50C878', '#50C878'), ('#F4C430', '#F4C430'), ('#007FFF', '#007FFF')], max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_image')),
            ],
        ),
        migrations.CreateModel(
            name='Color5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Maroon', 'Maroon'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Teal', 'Teal'), ('Lime', 'Lime'), ('Beige', 'Beige'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Violet', 'Violet'), ('Indigo', 'Indigo'), ('Turquoise', 'Turquoise'), ('Lavender', 'Lavender'), ('Crimson', 'Crimson'), ('Coral', 'Coral'), ('Peach', 'Peach'), ('Mint', 'Mint'), ('Ivory', 'Ivory'), ('Charcoal', 'Charcoal'), ('Burgundy', 'Burgundy'), ('Rose', 'Rose'), ('Emerald', 'Emerald'), ('Saffron', 'Saffron'), ('Azure', 'Azure')], max_length=100, null=True)),
                ('color_code', models.CharField(blank=True, choices=[('#000000', '#000000'), ('#FFFFFF', '#FFFFFF'), ('#FF0000', '#FF0000'), ('#0000FF', '#0000FF'), ('#008000', '#008000'), ('#FFFF00', '#FFFF00'), ('#FFA500', '#FFA500'), ('#800080', '#800080'), ('#FFC0CB', '#FFC0CB'), ('#808080', '#808080'), ('#A52A2A', '#A52A2A'), ('#00FFFF', '#00FFFF'), ('#FF00FF', '#FF00FF'), ('#800000', '#800000'), ('#000080', '#000080'), ('#808000', '#808000'), ('#008080', '#008080'), ('#00FF00', '#00FF00'), ('#F5F5DC', '#F5F5DC'), ('#FFD700', '#FFD700'), ('#C0C0C0', '#C0C0C0'), ('#EE82EE', '#EE82EE'), ('#4B0082', '#4B0082'), ('#40E0D0', '#40E0D0'), ('#E6E6FA', '#E6E6FA'), ('#DC143C', '#DC143C'), ('#FF7F50', '#FF7F50'), ('#FFE5B4', '#FFE5B4'), ('#98FF98', '#98FF98'), ('#FFFFF0', '#FFFFF0'), ('#36454F', '#36454F'), ('#800020', '#800020'), ('#FF007F', '#FF007F'), ('#50C878', '#50C878'), ('#F4C430', '#F4C430'), ('#007FFF', '#007FFF')], max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_image')),
            ],
        ),
        migrations.CreateModel(
            name='Color6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Maroon', 'Maroon'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Teal', 'Teal'), ('Lime', 'Lime'), ('Beige', 'Beige'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Violet', 'Violet'), ('Indigo', 'Indigo'), ('Turquoise', 'Turquoise'), ('Lavender', 'Lavender'), ('Crimson', 'Crimson'), ('Coral', 'Coral'), ('Peach', 'Peach'), ('Mint', 'Mint'), ('Ivory', 'Ivory'), ('Charcoal', 'Charcoal'), ('Burgundy', 'Burgundy'), ('Rose', 'Rose'), ('Emerald', 'Emerald'), ('Saffron', 'Saffron'), ('Azure', 'Azure')], max_length=100, null=True)),
                ('color_code', models.CharField(blank=True, choices=[('#000000', '#000000'), ('#FFFFFF', '#FFFFFF'), ('#FF0000', '#FF0000'), ('#0000FF', '#0000FF'), ('#008000', '#008000'), ('#FFFF00', '#FFFF00'), ('#FFA500', '#FFA500'), ('#800080', '#800080'), ('#FFC0CB', '#FFC0CB'), ('#808080', '#808080'), ('#A52A2A', '#A52A2A'), ('#00FFFF', '#00FFFF'), ('#FF00FF', '#FF00FF'), ('#800000', '#800000'), ('#000080', '#000080'), ('#808000', '#808000'), ('#008080', '#008080'), ('#00FF00', '#00FF00'), ('#F5F5DC', '#F5F5DC'), ('#FFD700', '#FFD700'), ('#C0C0C0', '#C0C0C0'), ('#EE82EE', '#EE82EE'), ('#4B0082', '#4B0082'), ('#40E0D0', '#40E0D0'), ('#E6E6FA', '#E6E6FA'), ('#DC143C', '#DC143C'), ('#FF7F50', '#FF7F50'), ('#FFE5B4', '#FFE5B4'), ('#98FF98', '#98FF98'), ('#FFFFF0', '#FFFFF0'), ('#36454F', '#36454F'), ('#800020', '#800020'), ('#FF007F', '#FF007F'), ('#50C878', '#50C878'), ('#F4C430', '#F4C430'), ('#007FFF', '#007FFF')], max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_image')),
            ],
        ),
        migrations.CreateModel(
            name='Color7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Maroon', 'Maroon'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Teal', 'Teal'), ('Lime', 'Lime'), ('Beige', 'Beige'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Violet', 'Violet'), ('Indigo', 'Indigo'), ('Turquoise', 'Turquoise'), ('Lavender', 'Lavender'), ('Crimson', 'Crimson'), ('Coral', 'Coral'), ('Peach', 'Peach'), ('Mint', 'Mint'), ('Ivory', 'Ivory'), ('Charcoal', 'Charcoal'), ('Burgundy', 'Burgundy'), ('Rose', 'Rose'), ('Emerald', 'Emerald'), ('Saffron', 'Saffron'), ('Azure', 'Azure')], max_length=100, null=True)),
                ('color_code', models.CharField(blank=True, choices=[('#000000', '#000000'), ('#FFFFFF', '#FFFFFF'), ('#FF0000', '#FF0000'), ('#0000FF', '#0000FF'), ('#008000', '#008000'), ('#FFFF00', '#FFFF00'), ('#FFA500', '#FFA500'), ('#800080', '#800080'), ('#FFC0CB', '#FFC0CB'), ('#808080', '#808080'), ('#A52A2A', '#A52A2A'), ('#00FFFF', '#00FFFF'), ('#FF00FF', '#FF00FF'), ('#800000', '#800000'), ('#000080', '#000080'), ('#808000', '#808000'), ('#008080', '#008080'), ('#00FF00', '#00FF00'), ('#F5F5DC', '#F5F5DC'), ('#FFD700', '#FFD700'), ('#C0C0C0', '#C0C0C0'), ('#EE82EE', '#EE82EE'), ('#4B0082', '#4B0082'), ('#40E0D0', '#40E0D0'), ('#E6E6FA', '#E6E6FA'), ('#DC143C', '#DC143C'), ('#FF7F50', '#FF7F50'), ('#FFE5B4', '#FFE5B4'), ('#98FF98', '#98FF98'), ('#FFFFF0', '#FFFFF0'), ('#36454F', '#36454F'), ('#800020', '#800020'), ('#FF007F', '#FF007F'), ('#50C878', '#50C878'), ('#F4C430', '#F4C430'), ('#007FFF', '#007FFF')], max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_image')),
            ],
        ),
        migrations.CreateModel(
            name='Color8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Maroon', 'Maroon'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Teal', 'Teal'), ('Lime', 'Lime'), ('Beige', 'Beige'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Violet', 'Violet'), ('Indigo', 'Indigo'), ('Turquoise', 'Turquoise'), ('Lavender', 'Lavender'), ('Crimson', 'Crimson'), ('Coral', 'Coral'), ('Peach', 'Peach'), ('Mint', 'Mint'), ('Ivory', 'Ivory'), ('Charcoal', 'Charcoal'), ('Burgundy', 'Burgundy'), ('Rose', 'Rose'), ('Emerald', 'Emerald'), ('Saffron', 'Saffron'), ('Azure', 'Azure')], max_length=100, null=True)),
                ('color_code', models.CharField(blank=True, choices=[('#000000', '#000000'), ('#FFFFFF', '#FFFFFF'), ('#FF0000', '#FF0000'), ('#0000FF', '#0000FF'), ('#008000', '#008000'), ('#FFFF00', '#FFFF00'), ('#FFA500', '#FFA500'), ('#800080', '#800080'), ('#FFC0CB', '#FFC0CB'), ('#808080', '#808080'), ('#A52A2A', '#A52A2A'), ('#00FFFF', '#00FFFF'), ('#FF00FF', '#FF00FF'), ('#800000', '#800000'), ('#000080', '#000080'), ('#808000', '#808000'), ('#008080', '#008080'), ('#00FF00', '#00FF00'), ('#F5F5DC', '#F5F5DC'), ('#FFD700', '#FFD700'), ('#C0C0C0', '#C0C0C0'), ('#EE82EE', '#EE82EE'), ('#4B0082', '#4B0082'), ('#40E0D0', '#40E0D0'), ('#E6E6FA', '#E6E6FA'), ('#DC143C', '#DC143C'), ('#FF7F50', '#FF7F50'), ('#FFE5B4', '#FFE5B4'), ('#98FF98', '#98FF98'), ('#FFFFF0', '#FFFFF0'), ('#36454F', '#36454F'), ('#800020', '#800020'), ('#FF007F', '#FF007F'), ('#50C878', '#50C878'), ('#F4C430', '#F4C430'), ('#007FFF', '#007FFF')], max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_image')),
            ],
        ),
        migrations.CreateModel(
            name='Color9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Maroon', 'Maroon'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Teal', 'Teal'), ('Lime', 'Lime'), ('Beige', 'Beige'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Violet', 'Violet'), ('Indigo', 'Indigo'), ('Turquoise', 'Turquoise'), ('Lavender', 'Lavender'), ('Crimson', 'Crimson'), ('Coral', 'Coral'), ('Peach', 'Peach'), ('Mint', 'Mint'), ('Ivory', 'Ivory'), ('Charcoal', 'Charcoal'), ('Burgundy', 'Burgundy'), ('Rose', 'Rose'), ('Emerald', 'Emerald'), ('Saffron', 'Saffron'), ('Azure', 'Azure')], max_length=100, null=True)),
                ('color_code', models.CharField(blank=True, choices=[('#000000', '#000000'), ('#FFFFFF', '#FFFFFF'), ('#FF0000', '#FF0000'), ('#0000FF', '#0000FF'), ('#008000', '#008000'), ('#FFFF00', '#FFFF00'), ('#FFA500', '#FFA500'), ('#800080', '#800080'), ('#FFC0CB', '#FFC0CB'), ('#808080', '#808080'), ('#A52A2A', '#A52A2A'), ('#00FFFF', '#00FFFF'), ('#FF00FF', '#FF00FF'), ('#800000', '#800000'), ('#000080', '#000080'), ('#808000', '#808000'), ('#008080', '#008080'), ('#00FF00', '#00FF00'), ('#F5F5DC', '#F5F5DC'), ('#FFD700', '#FFD700'), ('#C0C0C0', '#C0C0C0'), ('#EE82EE', '#EE82EE'), ('#4B0082', '#4B0082'), ('#40E0D0', '#40E0D0'), ('#E6E6FA', '#E6E6FA'), ('#DC143C', '#DC143C'), ('#FF7F50', '#FF7F50'), ('#FFE5B4', '#FFE5B4'), ('#98FF98', '#98FF98'), ('#FFFFF0', '#FFFFF0'), ('#36454F', '#36454F'), ('#800020', '#800020'), ('#FF007F', '#FF007F'), ('#50C878', '#50C878'), ('#F4C430', '#F4C430'), ('#007FFF', '#007FFF')], max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_image')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_orders', models.PositiveIntegerField()),
                ('total_products_sold', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('current_stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart_total_item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, choices=[('Accessories', 'Accessories'), ('T-Shirt', 'T-Shirt'), ('Bags', 'Bags'), ('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Footwear', 'Footwear'), ('Headwear', 'Headwear'), ('Hoodies', 'Hoodies'), ('Shoes', 'Shoes')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('promotion', models.TextField(blank=True, null=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Item.category')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.ManyToManyField(blank=True, to='Item.color1')),
                ('color10', models.ManyToManyField(blank=True, to='Item.color10')),
                ('color2', models.ManyToManyField(blank=True, to='Item.color2')),
                ('color3', models.ManyToManyField(blank=True, to='Item.color3')),
                ('color4', models.ManyToManyField(blank=True, to='Item.color4')),
                ('color5', models.ManyToManyField(blank=True, to='Item.color5')),
                ('color6', models.ManyToManyField(blank=True, to='Item.color6')),
                ('color7', models.ManyToManyField(blank=True, to='Item.color7')),
                ('color8', models.ManyToManyField(blank=True, to='Item.color8')),
                ('color9', models.ManyToManyField(blank=True, to='Item.color9')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_image', models.ImageField(upload_to='shirt_main_images/')),
                ('color', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Maroon', 'Maroon'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Teal', 'Teal'), ('Lime', 'Lime'), ('Beige', 'Beige'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Violet', 'Violet'), ('Indigo', 'Indigo'), ('Turquoise', 'Turquoise'), ('Lavender', 'Lavender'), ('Crimson', 'Crimson'), ('Coral', 'Coral'), ('Peach', 'Peach'), ('Mint', 'Mint'), ('Ivory', 'Ivory'), ('Charcoal', 'Charcoal'), ('Burgundy', 'Burgundy'), ('Rose', 'Rose'), ('Emerald', 'Emerald'), ('Saffron', 'Saffron'), ('Azure', 'Azure')], max_length=9, null=True)),
                ('size', models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXXL', 'Triple Extra Large')], max_length=4, null=True)),
                ('bag_size', models.CharField(blank=True, choices=[('6 x 8 inch', '7 x 9 inch'), ('8 x 11 inch', '8 x 11 inch'), ('7 x 9 inch', '7 x 9 inch'), ('9 x 12 inch', '9 x 12 inch'), ('10 x 15 inch', '12 x 16 inch')], max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('colors', models.ManyToManyField(to='Item.colors')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_user_id', models.CharField(max_length=100)),
                ('custom_identifiers', models.ManyToManyField(to='Item.customidentifier')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('billing_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_orders', to='Item.address')),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_orders', to='Item.address')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.cartitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cart_item', models.ManyToManyField(blank=True, related_name='cart_item', to='Item.cartitem')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='Item.orderitem'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('Stripe', 'Stripe'), ('Authorize.net', 'Authorize.net '), ('Bank Transfer', 'Bank Transfer')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('order', models.ManyToManyField(related_name='order_payment', to='Item.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payment', to='Item.payment'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('product_variant_id', models.CharField(max_length=100, unique=True)),
                ('product_image', models.URLField(blank=True, null=True)),
                ('product_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='product_image', null=True, upload_to='image')),
                ('discount_percentage', models.PositiveIntegerField(blank=True, default='3', null=True)),
                ('category_name', models.CharField(blank=True, choices=[('Accessories', 'Accessories'), ('T-Shirt', 'T-Shirt'), ('Bags', 'Bags'), ('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Footwear', 'Footwear'), ('Headwear', 'Headwear'), ('Hoodies', 'Hoodies'), ('Shoes', 'Shoes')], max_length=20, null=True)),
                ('product_card_name', models.CharField(default='Acme Circles T-Shirt', max_length=100)),
                ('name', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('popularity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flash_sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_flash_sale', to='Item.flashsale')),
                ('price_in_currencies', models.ManyToManyField(blank=True, related_name='item_currencies', to='Item.price')),
                ('product_details', models.ManyToManyField(to='Item.details')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='Item.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='products',
            field=models.ManyToManyField(blank=True, to='Item.product'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='flashsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale_product', to='Item.product'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Image', models.URLField(blank=True, null=True)),
                ('Product_url', models.URLField(blank=True, null=True)),
                ('Stock_Status', models.PositiveIntegerField(default=0)),
                ('Discount_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Product_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Item.product')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percentage', models.PositiveIntegerField()),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, to='Item.category')),
                ('applicable_products', models.ManyToManyField(blank=True, to='Item.product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(related_name='categories', to='Item.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='Item.CartItem', to='Item.product'),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('carrier', models.CharField(max_length=50)),
                ('shipped_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_delivery', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('Snaply', models.BooleanField(blank=True, null=True)),
                ('Standard', models.BooleanField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_order', to='Item.order')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Item.shipment'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_shipment', to='Item.shipment'),
        ),
        migrations.CreateModel(
            name='TotalCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_Quantity', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_stock',
            field=models.ManyToManyField(through='Item.Inventory', to='Item.warehouse'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='Item.product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('external_identifiers', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Item.externalidentifier')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
                ('wishlist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist', to='Item.wishlist')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Item.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_products', models.ManyToManyField(to='Item.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
