# Generated by Django 5.1 on 2024-12-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='user_profilePic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
