# Generated by Django 5.1 on 2024-12-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0002_productreview_user_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='profile_names',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
