# Generated by Django 5.1 on 2024-12-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0003_productreview_profile_names'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color3',
            new_name='Color',
        ),
        migrations.RemoveField(
            model_name='colors',
            name='color1',
        ),
        migrations.RemoveField(
            model_name='colors',
            name='color10',
        ),
        migrations.RemoveField(
            model_name='colors',
            name='color2',
        ),
        migrations.RemoveField(
            model_name='colors',
            name='color4',
        ),
        migrations.RemoveField(
            model_name='colors',
            name='color5',
        ),
        migrations.RemoveField(
            model_name='colors',
            name='color6',
        ),
        migrations.RemoveField(
            model_name='colors',
            name='color7',
        ),
        migrations.RemoveField(
            model_name='colors',
            name='color8',
        ),
        migrations.RemoveField(
            model_name='colors',
            name='color9',
        ),
        migrations.RenameField(
            model_name='colors',
            old_name='color3',
            new_name='color',
        ),
        migrations.DeleteModel(
            name='Color1',
        ),
        migrations.DeleteModel(
            name='Color10',
        ),
        migrations.DeleteModel(
            name='Color2',
        ),
        migrations.DeleteModel(
            name='Color4',
        ),
        migrations.DeleteModel(
            name='Color5',
        ),
        migrations.DeleteModel(
            name='Color6',
        ),
        migrations.DeleteModel(
            name='Color7',
        ),
        migrations.DeleteModel(
            name='Color8',
        ),
        migrations.DeleteModel(
            name='Color9',
        ),
    ]
