# Generated by Django 5.1 on 2024-11-26 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_subtotal', models.IntegerField(blank=True, null=True)),
                ('amount_total', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment_intent', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment_method_types', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
            ],
        ),
    ]
