# Generated by Django 5.1 on 2024-11-26 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_paymentsuccess_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.paymentsuccess')),
            ],
        ),
    ]
